### ISSUE TITLE
Incorrect link to book?

### ISSUE THREAD

**Issue by homerhanumat** [dcernst/IBL-IntroToProof#148]
On the main page for the repository, the link to the book site is given as [http://dcernst.github.com/IBL-IntroToProof](http://dcernst.github.com/IBL-IntroToProof) which leads nowhere.  Probably you wanted [http://dcernst.github.io/IBL-IntroToProof](http://dcernst.github.io/IBL-IntroToProof).

**Comment by dcernst** [comment]
Ah, thanks!  I'll fix this now.
