### ISSUE TITLE
Typo in Problem 8.66?

### ISSUE THREAD

**Issue by farmanb** [dcernst/IBL-IntroToProof#150]
I think there's a minor issue in Problem 8.66 on p.128 of the printed version.  Either it's a typo (maybe a fragment left over from a change?) or I've misunderstood the statement:

> Let $X = \\{a, b \\}$ and $Y = \\{ 1,2 \\}$.
>(a) Provide an example of a function that has a left inverse but does not have a right inverse.  Find the left inverse of your proposed function.
>(b) Provide an example of a function that has a right inverse but does not have a left inverse. Find the right inverse of your proposed function.

Based on context, I assume the reader is to find a function $f \colon X \to Y$ with the desired properties.  However, in this case, $f$ has a left inverse $\Leftrightarrow$ $f$ is injective $\Leftrightarrow$ $f$ is bijective $\Leftrightarrow$ $f$ has a right inverse.  

Are the sets $X$ and $Y$ supposed to have different cardinalities?

**Comment by dcernst** [comment]
I wish I could discover the origin of these errors sometimes.  Not sure how this one happened.  I will replace "Let $X=\{a,b\}$ and $Y=\{1,2\}$" with "Complete each of the following. Consider using finite sets and drawing a function diagram to define your functions."
