### ISSUE TITLE
Theorem 7.47 (Spring 2020) seems misplaced

### ISSUE THREAD

**Issue by dcernst** [dcernst/IBL-IntroToProof#77]
This theorem is the "first isomorphism theorem for sets".  It doesn't really make sense where it is.  It's not wrong, but maybe earlier would be better.

**Comment by StevenGubkin** [comment]
This section could also have some "factorization" theorems.  The whole section is kind of diagram chasing in SET, and it would be fun to have some theorems along the lines of the ones I mention here:

https://mathoverflow.net/questions/41955/does-any-textbook-take-this-approach-to-the-isomorphism-theorems

**Comment by dcernst** [comment]
I totally agree! I think this might be an instance where I have to resist temptation to add too many new ideas. On the other hand, it would be awesome if students could wrestle early with these fundamental ideas.

**Comment by dcernst** [comment]
Done.
