### ISSUE TITLE
Definition 7.11 is nonstandard

### ISSUE THREAD

**Issue by StevenGubkin** [dcernst/IBL-IntroToProof#80]
I would prefer if injectivity were defined as "For all x_1, x_2 in X, if f(x_1)=f(x_2) then x_1 = x_2".  This is also the first time "unique" has appeared, and the general proof strategy of showing that something is unique by showing any arbitrary two of them must be identical has not been introduced.  Might be good to have some more examples of this earlier, and give an explicit "proof skeleton" for it.

**Comment by dcernst** [comment]
The current Remark 7.12 (Spring 2020) unpacks Definition 7.11 as you suggest. I don’t think the current definition is is nonstandard. I like that one has to unpack the meaning of “uniqueness” in this case as informs the approach one must take to prove that a function is 1-1. This makes me realize that I should probably retool Remark 7.12 and create a task that gets the students to unpack “uniqueness” in this context.

You are absolutely correct that their should be a skeleton for “uniqueness” and potentially some example earlier.

**Comment by dcernst** [comment]
I'm going to add a section on "existence and uniqueness" in Chapter 2.
