### ISSUE TITLE
6.11 is a bit weird

### ISSUE THREAD

**Issue by StevenGubkin** [dcernst/IBL-IntroToProof#81]
6.11 says "Let A be the set of all differentiable functions on (0,1), and let B be the set of all derivatives of functions in A evaluated at x=0.5.  Describe the elements of the set AxB".

To my way of thinking, B is just \mathbb{R} with a very complicated description.

Was this intentional, trying to trick students into thinking that this set was {(f,f'(0.5)): f \in A} and have a conversation about why it is not?

In general a "teachers addition" with some indication of the point of some of these exercises might be helpful.  There are often really nice discussions which come out of these sorts of things (like, in another exercise, how "parallel" is either an equivalence relation or not depending on whether you consider a line to be parallel to itself).

**Comment by dcernst** [comment]
I agree that this isn’t the best example/exercise. There are better examples that could replace this. I’m open to suggestions.

As for a “Teacher’s Edition”, it’s something I have in the back of my mind. As I make revisions for the AMS version to be published, I may have to do this. I often mentor folks using the book, so I’ve been able to communicate my thinking to people directly, but there appear to be lots of people using the materials that I don’t even know about.

**Comment by dcernst** [comment]
I ended up removing this problem.
